"""initial migration

Revision ID: 98e7955c59ab
Revises: 
Create Date: 2025-06-14 16:28:48.515848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98e7955c59ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aeroporto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codice_iata', sa.String(length=3), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('città', sa.String(length=100), nullable=False),
    sa.Column('paese', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codice_iata')
    )
    op.create_table('utente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('nome', sa.String(length=64), nullable=True),
    sa.Column('cognome', sa.String(length=64), nullable=True),
    sa.Column('is_airline', sa.Boolean(), nullable=True),
    sa.Column('data_registrazione', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('compagnia_aerea',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nome_compagnia', sa.String(length=100), nullable=False),
    sa.Column('codice_iata', sa.String(length=2), nullable=False),
    sa.Column('sede_legale', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['utente.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codice_iata')
    )
    op.create_table('prenotazione',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('data_prenotazione', sa.DateTime(), nullable=True),
    sa.Column('stato', sa.String(length=20), nullable=True),
    sa.Column('prezzo_totale', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['utente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('volo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('airline_id', sa.Integer(), nullable=False),
    sa.Column('numero_volo', sa.String(length=10), nullable=False),
    sa.Column('departure_airport_id', sa.Integer(), nullable=False),
    sa.Column('arrival_airport_id', sa.Integer(), nullable=False),
    sa.Column('data_partenza', sa.DateTime(), nullable=False),
    sa.Column('data_arrivo', sa.DateTime(), nullable=False),
    sa.Column('posti_totali', sa.Integer(), nullable=False),
    sa.Column('posti_economy', sa.Integer(), nullable=False),
    sa.Column('posti_business', sa.Integer(), nullable=False),
    sa.Column('posti_first', sa.Integer(), nullable=False),
    sa.Column('prezzo_economy', sa.Float(), nullable=False),
    sa.Column('prezzo_business', sa.Float(), nullable=False),
    sa.Column('prezzo_first', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['airline_id'], ['compagnia_aerea.id'], ),
    sa.ForeignKeyConstraint(['arrival_airport_id'], ['aeroporto.id'], ),
    sa.ForeignKeyConstraint(['departure_airport_id'], ['aeroporto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('biglietto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('classe', sa.String(length=20), nullable=False),
    sa.Column('numero_posto', sa.String(length=10), nullable=True),
    sa.Column('prezzo', sa.Float(), nullable=False),
    sa.Column('bagaglio_extra', sa.Boolean(), nullable=True),
    sa.Column('servizi_extra', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['prenotazione.id'], ),
    sa.ForeignKeyConstraint(['flight_id'], ['volo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('biglietto')
    op.drop_table('volo')
    op.drop_table('prenotazione')
    op.drop_table('compagnia_aerea')
    op.drop_table('utente')
    op.drop_table('aeroporto')
    # ### end Alembic commands ###
